### ISSUE TITLE
tryk8s link not working 

### ISSUE THREAD

**Issue by akiffeyzioglu** [learnk8s/free-kubernetes#10]
Website get "DNS_PROBE_FINISHED_NXDOMAIN" error.

**Comment by salaboy** [comment]
Thanks for reporting this.. I will check and create a separate category, we should report that back to that team

**Comment by salaboy** [comment]
@akiffeyzioglu I've created an issue linked to this to see if we can resolve this. Let's wait a couple of days before removing tryk8s from the list.

**Comment by akiffeyzioglu** [comment]
Ok. Thanks.

**Comment by ShubhamTatvamasi** [comment]
@salaboy it's still not working.

**Comment by salaboy** [comment]
@ShubhamTatvamasi fair enough let's remove it

**Comment by salaboy** [comment]
removed
