### ISSUE TITLE
Credit card required for Civo cloud

### ISSUE THREAD

**Issue by hrittikhere** [learnk8s/free-kubernetes#18]
Civo Cloud
Description: Monthly $70 discount for managed k3s cluster
Details: https://www.civo.com/learn/kubernetes-faq
Bonus: No Credit Card is required to get 70$ free credit
Link: https://www.civo.com/kube100

I think the offer is no longer valid. Can you please update/check the entry? 
CC: @saiyam1814
![image](https://user-images.githubusercontent.com/67012359/126520122-372b439a-6cd5-47d4-9e20-cfb06e4a3269.png)

**Comment by salaboy** [comment]
@hrittikhere thanks for reporting this .. I will check it out.

**Comment by saiyam1814** [comment]
Hi @hrittikhere Thanks for reporting , so May2021 we came out of beta and the $70 thing ended. 
You can still signup using a credit card and get $250 free on signup. 
I can fix that in the repo

**Comment by saiyam1814** [comment]
this is fixed in #19

**Comment by salaboy** [comment]
Done
