### ISSUE TITLE
Katacoda no longer available

### ISSUE THREAD

**Issue by Waqas-Shah-42** [learnk8s/free-kubernetes#25]
Katacoda has been bought by O’Reilly and is no longer available. https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html

**Comment by HelixSpiral** [comment]
I have an open PR for removing this: #24

**Comment by ilovelinux** [comment]
PR has been merged, please close the issue (cc @salaboy)

**Comment by salaboy** [comment]
@ilovelinux closed
