### ISSUE TITLE
Add aws in the list

### ISSUE THREAD

**Issue by that-coder** [learnk8s/free-kubernetes#3]

**Comment by salaboy** [comment]
@that-coder well, but AWS EKS not free to use.. so what are you suggesting?

**Comment by salaboy** [comment]
@that-coder if you have a way to use AWS EKS trial without paying please share links

**Comment by salaboy** [comment]
Closing as EKS is not free, please @that-coder reopen if you find any discount links that can be used to not pay for it

**Comment by that-coder** [comment]
You were right about EKS. There is no trial period for EKS. But I don't know, if there is an option inside fargate to do this

**Comment by salaboy** [comment]
@that-coder 👍
