### ISSUE TITLE
End of support for okteto cloud

### ISSUE THREAD

**Issue by srikanth-iyengar** [learnk8s/free-kubernetes#32]
Okteto cloud is discontinuing the free tier for the individuals. This changes will be in effect from 15th of January 2024
[link](https://www.okteto.com/blog/empowering-teams-the-shift-in-okteto-development-focus/?_hsmi=286558590&_hsenc=p2ANqtz-_x1XZHtxkw2K97rlu7i96UqAmhyK2xSFkR8x5vTSjEEnp93S-P7i53Zedh-w7UNAUiz_6ViDJkSFlnzvpZ7U5MT22_1Q)

**Comment by danielepolencic** [comment]
Removed Okteto
